{
 "title": "Kubernetes Audit Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Cluster Activated Top User Agents",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(100, sum by (userAgent) (count_over_time({filename=\"/var/log/kubernetes/audit/audit.log\"} | json |  __error__=\"\" [$__interval])))",
     "legendFormat": "{{http_user_agent}}"
    }
   ]
  },
  {
   "title": "ExecAttemption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=\"/var/log/kubernetes/audit/audit.log\"}|json|objectRef_subresource=\"exec\"[5m]))",
     "legendFormat": "curl/requests"
    }
   ]
  },
  {
   "title": "WatchObjectCalls",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({filename=\"/var/log/kubernetes/audit/audit.log\"}|json|verb=\"watch\"[5m]))",
     "legendFormat": "watch-events"
    }
   ]
  },
  {
   "title": "NonKubectlAccess",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=\"/var/log/kubernetes/audit/audit.log\"}|json|~ \"curl|requests\"[5m]))",
     "legendFormat": "curl/requests"
    }
   ]
  },
  {
   "title": "ForbiddenAccessAttemption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=\"/var/log/kubernetes/audit/audit.log\"}|json|annotations_authorization_k8s_io_decision=\"forbid\"[5m]))",
     "legendFormat": "curl/requests"
    }
   ]
  },
  {
   "title": "SecretsAccessCount",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=\"/var/log/kubernetes/audit/audit.log\"}|json|=\"/api/v1/secrets\"[5m]))",
     "legendFormat": "curl/requests"
    }
   ]
  },
  {
   "title": "ConfigmapAccessCount",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=\"/var/log/kubernetes/audit/audit.log\"}|json|=\"/api/v1/configmaps\"[5m]))",
     "legendFormat": "curl/requests"
    }
   ]
  },
  {
   "title": "UnAuthenticatedPodAttemptions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({filename=\"/var/log/kubernetes/audit/audit.log\"}|json|annotations_authorization_k8s_io_decision=\"forbid\"|=\"/api/v1/\"|=\"/pods\"[5m]))",
     "legendFormat": "pods-unauthenticated"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({filename=\"/var/log/kubernetes/audit/audit.log\"}|json|annotations_authorization_k8s_io_decision=\"forbid\"|=\"/api/v1/\"|=\"/deployments\"[5m]))",
     "legendFormat": "deployments-unauthenticated"
    }
   ]
  },
  {
   "title": "SecretsUnAuthenticated",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({filename=\"/var/log/kubernetes/audit/audit.log\"}|json|annotations_authorization_k8s_io_decision=\"forbid\"|=\"/api/v1/\"|=\"/secrets\"[5m]))",
     "legendFormat": "secrets-unauthenticated"
    }
   ]
  },
  {
   "title": "ConfigmapUnAuthenticated",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({filename=\"/var/log/kubernetes/audit/audit.log\"}|json|annotations_authorization_k8s_io_decision=\"forbid\"|=\"/api/v1/\"|=\"/configmaps\"[5m]))",
     "legendFormat": "configmap-unauthenticated"
    }
   ]
  },
  {
   "title": "ForbiddenUserActivity",
   "type": "logs",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/kubernetes/audit/audit.log\"} | json |annotations_authorization_k8s_io_decision=\"forbid\"| line_format \"User Agent: {{.userAgent}} UserName: {{.user}}\""
    }
   ]
  },
  {
   "title": "ExecAttemptions",
   "type": "logs",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/kubernetes/audit/audit.log\"} | json |objectRef_subresource=\"exec\"| line_format \"request for {{.requestURI}} with HTTP status: {{.responseStatus_code}} \""
    }
   ]
  },
  {
   "title": "Privileged ",
   "type": "logs",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/kubernetes/audit/audit.log\"}|json|=\"securityContext\\\":{\\\"privileged\\\":true}\"|line_format \"Privileged Pods : {{.responseObject_metadata_name}} \""
    }
   ]
  },
  {
   "title": "UsersExecAttemption",
   "type": "logs",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/kubernetes/audit/audit.log\"} | json |objectRef_subresource=\"exec\"| line_format \"User who executed something on pods {{.user_username}} \""
    }
   ]
  },
  {
   "title": "DeleteActions",
   "type": "logs",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/kubernetes/audit/audit.log\"} | json |verb=\"delete\"| line_format \"request for {{.requestURI}} with HTTP status: {{.responseStatus_code}} \""
    }
   ]
  },
  {
   "title": "NonAuthenticatedAccess",
   "type": "logs",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/kubernetes/audit/audit.log\"} | json |responseStatus_code=403| line_format \"request for {{.requestURI}} with HTTP status: {{.responseStatus_code}} \""
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "APIServerActivities",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/kubernetes/audit/audit.log\"} | json | line_format \"request for {{.requestURI}} with HTTP status: {{.responseStatus_code}} \""
    }
   ]
  }
 ]
}